// Writes dist/cad-viewer.cdn.js: the same component with its three.js imports
// rewritten to jsDelivr's ESM builds, so it runs from a plain <script
// type="module"> with no import map and no bundler.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const THREE_VERSION = '0.168.0';
const CDN = `https://cdn.jsdelivr.net/npm/three@${THREE_VERSION}`;

const src = readFileSync(new URL('../cad-viewer.js', import.meta.url), 'utf8');
const out = src
  .replace(/from 'three';/g, `from '${CDN}/+esm';`)
  .replace(/from 'three\/addons\/([^']+)';/g, (_, path) => `from '${CDN}/examples/jsm/${path}/+esm';`);

if (/from 'three/.test(out)) throw new Error('unrewritten three import left in the CDN build');
mkdirSync(new URL('../dist/', import.meta.url), { recursive: true });
writeFileSync(new URL('../dist/cad-viewer.cdn.js', import.meta.url),
  `// Generated by scripts/build-cdn.mjs from cad-viewer.js. Do not edit.\n${out}`);
console.log('wrote dist/cad-viewer.cdn.js');
